{
 "title": "Cloud Platform Metrics - AWS_Costs",
 "description": "Visualize estimated AWS costs per Namespace/Service",
 "tags": [
  "metrics",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hosted_ns",
    "query": {
     "query": "label_values(cloud_platform_metrics_aws_costs{}, hosted_ns)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PWS Service Costs $hosted_ns",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "cloud_platform_metrics_aws_costs{hosted_ns='$hosted_ns'}",
     "application": { "filter": "" },
     "dimensions": { "Currency": "USD" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "PWS Service Costs $hosted_ns",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "Currency": "USD", "ServiceName": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "AWS Service Costs $hosted_ns",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "AWS Namespace Costs $hosted_ns",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "sum (cloud_platform_metrics_aws_costs{hosted_ns='$hosted_ns'})",
     "application": { "filter": "" },
     "dimensions": { "Currency": "USD" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "AWS Namespace Costs $hosted_ns",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "Currency": "USD", "ServiceName": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "AWS Namespace Costs $hosted_ns",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "AWS Namespace Costs All Namespaces",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "sum (cloud_platform_metrics_aws_costs) by (hosted_ns)",
     "application": { "filter": "" },
     "dimensions": { "Currency": "USD" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "AWS Namespace Costs All Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "Currency": "USD", "ServiceName": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "AWS Namespace Costs All Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  { "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 } }
 ]
}