{
 "title": "cloud_platforms_performance_metrics",
 "description": "Visualize the cloud-platform's performance metrics",
 "tags": [
  "metrics",
  "monitoring"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "1. Cloud Platform's Incidents Mean Time To Repair",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cloud_platform_metrics_incidents_mean_time_to_repair",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "1. Cloud Platform's Incidents Mean Time To Repair",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "2. Cloud Platform's Incidents Mean Time To Resolve",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cloud_platform_metrics_incidents_mean_time_to_resolve",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "2. Cloud Platform's Incidents Mean Time To Resolve",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "3. Cloud Platform's Successful Infrastructure deployments",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (cloud_platform_metrics_infrastructure_deployment_details_deployed)",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "3. Cloud Platform's Successful Infrastructure deployments",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "4. Cloud Platform's Failed Infrastructure Deployments",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (cloud_platform_metrics_infrastructure_deployment_details_failed)",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "4. Cloud Platform's Failed Infrastructure deployments",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}