{
 "title": "namespace-metrics",
 "description": "Visualize estimated AWS costs per Namespace/Service",
 "tags": [
  "metrics",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total number of production Namespaces",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(cloud_platform_metrics_namespace_details{is_production='true'})",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Total number of production Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Total number of production Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Total number of non-production Namespaces",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(cloud_platform_metrics_namespace_details{is_production='false'})",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Total number of non-production Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Total number of non-production Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Total number of all Namespaces",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count(cloud_platform_metrics_namespace_details)",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Total number of all Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Total number of all Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  { "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 } }
 ]
}