apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-metrics-app
  template:
    metadata:
      labels:
        app: cp-metrics-app
    spec:
      containers:
        - name: cp-metrics-app
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: eu-west-2
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cp-metrics-aws-costs
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cp-metrics-aws-costs
                  key: secret_access_key
            - name: GITHUB_OAUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloud-platform-metrics-gh-token
                  key: token
