{
 "title": "cloud_platforms_aws_costs_metrics",
 "description": "Visualize estimated AWS costs per Namespace/Service",
 "tags": [
  "metrics",
  "monitoring"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hosted_ns",
    "query": {
     "query": "label_values(cloud_platform_metrics_aws_costs{}, hosted_ns)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "1. Cloud Platform's AWS Service Costs $hosted_ns",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "cloud_platform_metrics_aws_costs{hosted_ns='$hosted_ns'}",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "1. Cloud Platform's AWS Service Costs $hosted_ns",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "2. Cloud Platform's AWS Namespace Costs $hosted_ns",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "sum (cloud_platform_metrics_aws_costs{hosted_ns='$hosted_ns'})",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "2. Cloud Platform's AWS Namespace Costs $hosted_ns",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "3. Cloud Platform's Average AWS Cost Per Namespace",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "sum (cloud_platform_metrics_aws_costs)/count(cloud_platform_metrics_namespace_details)",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "3. Cloud Platform's Average AWS Cost Per Namespace",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "4. Cloud Platform's AWS Namespace Costs All Namespaces",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "sum (cloud_platform_metrics_aws_costs)",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "4. Cloud Platform's AWS Namespace Costs All Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}