{
 "title": "cloud_platforms_namespace_metrics",
 "description": "Visualize estimated AWS costs per Namespace/Service",
 "tags": [
  "metrics",
  "monitoring"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "1. Cloud Platform Total number of production Namespaces",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(cloud_platform_metrics_namespace_details{is_production='true'})",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "1. Cloud Platform Total number of production Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "2. Cloud Platform Total number of non-production Namespaces",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(cloud_platform_metrics_namespace_details{is_production='false'})",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "2. Cloud platform Total number of non-production Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "3. Cloud Platform Total number of all Namespaces",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count(cloud_platform_metrics_namespace_details)",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "3. Cloud Platform Total number of all Namespaces",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "4. Cloud Platform Unique Applications",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count(count(cloud_platform_metrics_namespace_details{application=~'.*'}) by (application))",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "4. Cloud Platform Unique Applications",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "5. Cloud Platform Unique Applications (Production)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count(count(cloud_platform_metrics_namespace_details{is_production='true', application=~'.*'}) by (application))",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "5. Cloud Platform Unique Applications (Production)",
     "namespace": "monitoring",
     "options": {
      "showDisabledItems": false
     },
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}